# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestFeedback():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_feedback(self):
    self.driver.get("http://127.0.0.1:5000")
    self.driver.find_element(By.LINK_TEXT, "Feedback").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "good")))
    self.driver.find_element(By.NAME, "comments").send_keys("good service")
    self.driver.find_element(By.NAME, "userid").send_keys("abiali")
    self.driver.find_element(By.NAME, "email").send_keys("abc@gmail.com")
    self.driver.find_element(By.ID, "send").click()
  
