# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTestcustneg2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcustneg2(self):
    self.driver.get("http://127.0.0.1:5000/")
    time.sleep(500)
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div/div[3]/span[2]/a").click()
    self.driver.find_element(By.NAME, "FName").send_keys("varun")
    self.driver.find_element(By.NAME, "lName").send_keys("chandak")
    self.driver.find_element(By.NAME, "username").send_keys("varun123")
    self.driver.find_element(By.NAME, "email").send_keys("varungmail.com")
    self.driver.find_element(By.NAME, "PhoneNumber").send_keys("9845662323")
    self.driver.find_element(By.NAME, "age").send_keys("21")
    self.driver.find_element(By.NAME, "Password").send_keys("varun")
    self.driver.find_element(By.NAME, "ConfirmPassword").send_keys("varun")
    dropdown = self.driver.find_element(By.XPATH, "//*[@id=\"squestion\"]")
    dropdown.find_element(By.XPATH, "//option[. = 'Your First Phone\'s Brand Name']").click()
    self.driver.find_element(By.NAME, "answer").send_keys("sony")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[10]").click()
    time.sleep(500)
  
