# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestForgetpassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_forgetpassword(self):
    print("`set speed` is a no-op in code export, use `pause` instead")
    self.driver.get("http://127.0.0.1:5000/login")
    self.driver.find_element(By.XPATH, "/html/body/div/div[3]/form/div[3]/ul/li/a").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[1]").send_keys("abiali")
    dropdown = self.driver.find_element(By.ID, "squestion")
    dropdown.find_element(By.XPATH, "//option[. = 'Your First School Name']").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[2]").send_keys("chavara")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[3]").send_keys("abiali123")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[4]").send_keys("abiali123")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[5]").click()
  
