# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestMaintestadmin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def admindashboard(self):
 #   [object Object]
    self.loginpositiveadmin()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[1]/a[1]").click()
 #   [object Object]
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li/a").click()
  
  def loginpositiveadmin(self):
    self.driver.get("http://127.0.0.1:5000")
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("ali")
    self.driver.find_element(By.ID, "passw").send_keys("password")
  #  [object Object]
    self.driver.find_element(By.NAME, "proceed").click()
    assert self.driver.title == "Admin Page"
   # [object Object]
   
  def test_manageadmin(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[1]/a[2]").click()
    #time.sleep(1000)
   
    #self.test_addadmin()
    
    
  def test_addadmin(self):
    #time.sleep(1000)
    self.driver.get("http://127.0.0.1:5000/addadmin/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[1]").send_keys("mayur")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[2]").send_keys("deshmukh")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[3]").send_keys("mayur1092")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[4]").send_keys("mayur.s.deshmukh@gmail.com")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[5]").send_keys("9154455432")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[6]").send_keys("21")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[7]").send_keys("root")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[8]").send_keys("root")
    dropdown = self.driver.find_element(By.ID, "squestion")
    dropdown.find_element(By.XPATH, "//option[. = 'Your First School Name']").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[9]").send_keys("symbioses")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[10]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()  
    
  def test_removeadmin(self):
    #self.driver.get("http://127.0.0.1:5000/addadmin/")
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[4]/a").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[1]").send_keys("REAPER")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[2]").send_keys("mayur1092")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[3]").send_keys("ali")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[4]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()
    #print("`set speed` is a no-op in code export, use `pause` instead")
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()
    #time.sleep(1000)
    
  def test_managecustomers(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[1]/a[3]").click()
  
  def test_managedriver(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[1]/a[4]").click()
    
  def test_adddriver(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/adddriver/")
    self.driver.find_element(By.NAME, "dfname").send_keys("raj")
    self.driver.find_element(By.NAME, "dlname").send_keys("kumar")
    self.driver.find_element(By.NAME, "dphone").send_keys("9856773452")
    self.driver.find_element(By.NAME, "dage").send_keys("30")
    self.driver.find_element(By.NAME, "license").send_keys("D3245522")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[6]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()
    
  def test_removedriver(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/displaydrivers/")
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[4]/a").click()
    self.driver.find_element(By.NAME, "driverid").send_keys("raj")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/form/input[2]").click()
    
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()
    
    #time.sleep(1000)    
      
  def test_cardriveravailability(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[1]/center/a").click()  
    
  def test_changecarstatus(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/displaycarstatus/")
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()
    self.driver.find_element(By.NAME, "cari").send_keys("1")
    dropdown = self.driver.find_element(By.ID, "type")
    dropdown.find_element(By.XPATH, "//option[. = 'Available']").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[2]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[2]/a").click()  
   
  def test_changedriverstatus(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/displaydriverstatus/")
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[5]/a").click()
    self.driver.find_element(By.NAME, "driverid").send_keys("9")
    dropdown = self.driver.find_element(By.XPATH, "//*[@id=\"type\"]")
    dropdown.find_element(By.XPATH, "//option[. = 'Available']").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[2]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[4]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()
    
    
  def test_managecar(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[2]/a[1]").click()
    #time.sleep(1000)
   
    
  def test_addcar(self):
   # self.driver.get("http://127.0.0.1:5000/addcar/")
    self.driver.find_element(By.NAME, "carid").send_keys("10")
    self.driver.find_element(By.NAME, "model").send_keys("D3")
    self.driver.find_element(By.NAME, "registration").send_keys("345213")
    self.driver.find_element(By.NAME, "seating").send_keys("7")
    dropdown = self.driver.find_element(By.XPATH, "//*[@id=\"type\"]")
    dropdown.find_element(By.XPATH, "//option[. = 'SUV Car']").click()
    self.driver.find_element(By.NAME, "price").send_keys("10")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[6]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()
    #time.sleep(500)
    
  def test_removecar(self):
    #time.sleep(1000)
    #self.driver.get("http://127.0.0.1:5000/displaycars/")
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[4]/a").click()
    self.driver.find_element(By.NAME, "carid").send_keys("10")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/form/input[2]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()    
   
  def test_managefeedback(self):
    #self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[2]/a[2]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()
    #time.sleep(1000)
    
  def test_loginhistory(self):
    #self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[2]/a[3]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()
    #time.sleep(1000)
    
  
  def test_removecustomer(self):
    #time.sleep(1000)
   # self.driver.get("http://127.0.0.1:5000/displaycustomer/")
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[3]/a").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[1]").send_keys("varun123")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[2]").send_keys("ali")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/form/input[3]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[2]/a").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()
    
  def test_managebooking(self):
    #time.sleep(1000)
   # self.driver.get("http://127.0.0.1:5000/adminpage/")
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[2]/a[4]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"navbarNav\"]/ul/li[1]/a").click()
    
    #time.sleep(1000)
    
    
   
  
  def test_maintestadmin(self):
    self.admindashboard()
    self.test_manageadmin()
    print("Hello")
    self.test_addadmin()
    self.test_removeadmin()
    self.test_managecustomers()
    self.test_removecustomer()
    self.test_managedriver()
    self.test_adddriver()
    self.test_removedriver()
    self.test_cardriveravailability()
    self.test_changecarstatus()
    self.test_changedriverstatus()
    self.test_managecar()
    self.test_addcar()
    self.test_removecar()
    self.test_managefeedback()
    self.test_loginhistory()
    self.test_managebooking()
    #self.driver.find_element(By.XPATH,"//*[@id=\"navbarNav\"]/ul/li/a").click()
    self.driver.find_element(By.XPATH, "/html/body/div[2]/div/div/ul/li[3]/a").click()
    
Admin=TestMaintestadmin()
Admin.setup_method()
Admin.test_maintestadmin()
#Admin.teardown_method()    
  
